---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 
      ansible_user: 
vector:
  hosts:
    vector-01:
      ansible_host: 
      ansible_user: 
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 
      ansible_user: 